### ISSUE TITLE
starfighter.desktop and starfighter.png are missing from source tarballs

### ISSUE THREAD

**Issue by keikebreau** [pr-starfighter/starfighter#1]
Hello,

I'm looking to update the Project: Starfighter package for the GNU/Linux distribution I use. However, the installation fails because the [starfighter.desktop](https://github.com/pr-starfighter/starfighter/blob/master/misc/starfighter.desktop) and [starfighter.png](https://github.com/pr-starfighter/starfighter/blob/master/misc/starfighter.png) files are missing from the "misc" folder of the source tarballs.

These files were present in the source tarballs of version 1.7, so I wonder whether or not their exclusion in version 2.0 and up is intentional.

Thanks,
mindfodder

**Comment by onpon4** [comment]
Thank you for the report! It seems Autoconf isn't configured properly to include those files in the "make dist" command, hence the oversight. I will correct this as soon as possible. In the meantime, please use the auto-generated "source code" downloads (at the bottom of the list of files). You'll have to install Autotools and do "autoreconf -vif" to generate the configure script; everything else should work as normal.

**Comment by onpon4** [comment]
Alright, the problem has been fixed! You can find the updated files in the place the old files were. Please let me know if you continue to experience any further problems.

**Comment by keikebreau** [comment]
Thanks! Building from the cloned repository and auto-generated tarball works as expected.

As for the new tarball, the installation phase fails when installing the "locale/en" folder as part of the "install-nobase_dist_pkgdataDATA" target. When "locale/en" is a file instead of a folder, the installation proceeds as intended. Interestingly, even using "autoreconf -vif" before configuring and building doesn't fix this. Should I open a separate issue?

**Comment by onpon4** [comment]
O_O Yeah, an issue on that would be nice, I've never had that happen before. Please include the error message you got. I'll also try to reproduce that on my own machine, hopefully later today.
