### ISSUE TITLE
Question : Pango

### ISSUE THREAD

**Issue by BeWorld2018** [pr-starfighter/starfighter#13]
I check Pango but this library is old and use GTK, not compatible with all machine :-( 
It's possible to find an alternative or remove it ?!

Thanks

**Comment by onpon4** [comment]
Is it? Wikipedia says the most recent release was last year and so far as I can tell it's not a part of GTK. What machines is it incompatible with?

As for replacing it, maybe, but it's the only library we were able to find to get info about UTF-8 characters from. If you want you can disable Unicode support with the SF_NOFONT flag (which will cause it to fall back to the old image-based text). In fact if Pango or SDL2_ttf is unavailable it will do this automatically.

🕵️

**Comment by BeWorld2018** [comment]
I use MorphOS (PowerPC machine - Mac), it's an AmigaOs compatible.
SDL2_ttf is ok but Pando not (i port a lot of game for this machine and starfighter is only to use it) :( , i ask that if it's easy to replace it... I compile Starfighter with NOFONT.
Thanks

**Comment by onpon4** [comment]
We could replace it but we need a replacement first. Specifically something that implements UAX \#14: http://www.unicode.org/reports/tr14/tr14-24.html

🕵️
