### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by fmneto** [pr-starfighter/starfighter#14]
[spelling-patch.tar.gz](https://github.com/pr-starfighter/starfighter/files/5136583/spelling-patch.tar.gz)

Found a couple of spelling errors in the source code while packaging this version for Debian. Patch file is attached.

**Comment by onpon4** [comment]
I've added this in and will be looking at the others. For future reference, it's much easier to merge a pull request or pull from a Git repo somewhere (where exactly doesn't matter, but if it's in a Git repo I can just do `git remote add <name> <url> && git pull <name> main`).

🕵️

**Comment by fmneto** [comment]
Noted for future reference :)
