### ISSUE TITLE
No manpage

### ISSUE THREAD

**Issue by fmneto** [pr-starfighter/starfighter#15]
Starfighter doesn't have a manpage. 

I'm sending a very basic one attached.
[sf-manpage.tar.gz](https://github.com/pr-starfighter/starfighter/files/5136247/sf-manpage.tar.gz)

**Comment by onpon4** [comment]
I've thrown that into the misc directory. I don't know anything about manpages, though, so I don't know what else to do with it (as far as installing and stuff). Leaving this open for now.

🕵️

**Comment by fmneto** [comment]
I'll try to adapt something a bit more comprehensive later.

**Comment by onpon4** [comment]
We've used that manpage as a template for the real manpage and now install it! Works successfully, so closing this now.

🕷️
