### ISSUE TITLE
tarball signature

### ISSUE THREAD

**Issue by fmneto** [pr-starfighter/starfighter#16]
The source tarball is no longer signed (as in the savannah days).

**Comment by onpon4** [comment]
They were signed on Savannah because Savannah seemed to require it. Is there a particular reason you want it signed?

🕵️

**Comment by fmneto** [comment]
Probably the same reasons savannah wanted them signed. Want to ensure they are what they say they are.

A healthy level of paranoia, some would say.

**Comment by fmneto** [comment]
Case in point: Debian requirements for packaging. I'm updating starfighter for the next release (current Stable still has version 1.7).

**Comment by onpon4** [comment]
OK. Well I've generated a PGP key and added it to my GitHub account but it seems I can't sign tags that already exist, so I don't know how to do this for sure. I *guess* I could manually create the v2.3.2 branch when that version is released and use that precreated tag for the GH releases thing.

Would doing this sooner rather than later affect what Debian release gets a Starfighter upgrade? I wasn't planning on making a new bugfix release right away but if it avoids missing a freeze period in Debian I can do so. (I suppose I'm asking for a sort of "deadline" to avoid Debian getting further behind on Starfighter updates.)

🕵️

**Comment by fmneto** [comment]
There is no rush. The Freeze should begin only in January, so we have plenty of time. :)

**Comment by onpon4** [comment]
Okey dokey, so a few months then. I should have a new release out sooner than that. I'll try to remember to sign it.

🕵️

**Comment by onpon4** [comment]
@fmneto We've made a new release and signed both the commit and the tag: https://github.com/pr-starfighter/starfighter/releases/tag/v2.3.2

Can you let me know if this is sufficient? I think / hope it should be, manually signing archives every release would be a pain. 😅

🕷️

**Comment by onpon4** [comment]
Just want to ping you on this again, @fmneto. We made another release and would like to know if this is sufficient or if you need us to do some additional thing. We've started auto-signing all commits and we've also started signing all release tags (not just for this project but for others as well). If Debian has further requirements we'd be perfectly willing to accommodate them. Just let us know.

🕵️

**Comment by fmneto** [comment]
Hey man, that's great news!

I'm dealing with some family stuff right now, but I'll update the packaging as soon as possible.

Cheers!

**Comment by fmneto** [comment]
Hey again @onpon4 !

I'll need the public key for the key you used to sign the tarball.

**Comment by onpon4** [comment]
The key ID is 5369030A6FBA50616EE78D5852FB5C20A8336782 and it's on keys.openpgp.org. Attached it here.

[githubkey.txt](https://github.com/pr-starfighter/starfighter/files/5477829/githubkey.txt)

🕵️

**Comment by fmneto** [comment]
Great! 

Ideally, it would be made available through a download link alongside the tarball. But this should work just as fine.

**Comment by fmneto** [comment]
Something I completely forgot to ask for: I need the signature file as well.

I've just realised that there has been a miscommunication here; having commits and tags signed is desirable, but what is required is that the actual tarball is signed. As in:

$ gpg --sign starfighter-2.3.2-src.tar.gz > starfighter-2.3.2-src.tar.gz.asc

The .asc file would contain the signature of the tarball. That's what I would actually need.

I'll point out that packaging will work _just fine_ without any of that, so this is getting packaged anyway. But adding a signed tarball would mean an extra layer of security.

**Comment by onpon4** [comment]
Is this a thing that projects often do? I've never seen it happen but that could just be my lack of experience.

I've attached what I think you're looking for.

[starfighter-2.3.3-src.tar.gz.sig.zip](https://github.com/pr-starfighter/starfighter/files/5507285/starfighter-2.3.3-src.tar.gz.sig.zip)

**Comment by fmneto** [comment]
Quite a lot of them don't, to be honest. The tag that comes up during package build is considered "pedantic". 

But here have been cases of attacks where the source code is modified without knowledge on the developer's part, so it's recommended. 

About the attached signature file, I wasn't able to verify it. Do you need assistance signing the tarball? Your key is pretty new, and GPG can be a challenge if you've never used it before. Let me know if you need help.

**Comment by onpon4** [comment]
That's a signature for https://github.com/pr-starfighter/starfighter/releases/download/v2.3.3/starfighter-2.3.3-src.tar.gz inside of a zip. Do you have the right archive, and did you extract the signature? (It's in a zip file because GitHub wouldn't let me attach a .sig file.)

**Comment by fmneto** [comment]
Ah, I see. I've been downloading the file from the link "Source code". It's the last one in the list. Any reason to offer two different packages with the source?

We are getting somewhere, I think! I've updated things to check for the correct tarball, and they check out. There is no need (on my part) for a .gpg file. All I need is that the signature file is made available alongside the tarball, and I'll get out of your hair ;)

**Comment by onpon4** [comment]
The ones on the bottom are supplied automatically by GitHub. They don't include the configure script or gettext builds, so (like with checking out the repo) they require extra steps and dependencies to build. (In fact they are literally just snapshots of the repo corresponding to the v2.3.3 tag.)

🕵️

**Comment by fmneto** [comment]
Got it. Can you share the .sig file alongside the tarball? That way the packaging scripts can grab it automagically and do their thing.

**Comment by onpon4** [comment]
I guess. I've added it to the files list. I'll try to remember to do that in later releases I suppose.

🕵️

**Comment by fmneto** [comment]
Awesome!

Thank you so much for your assistance. I'm closing this now. 

Cheers!!
