### ISSUE TITLE
Missing field in Desktop entry

### ISSUE THREAD

**Issue by fmneto** [pr-starfighter/starfighter#17]
There is a missing field (Keywords) in the Desktop entry. Patch file attached.
[fix-desktop-entry.tar.gz](https://github.com/pr-starfighter/starfighter/files/5136589/fix-desktop-entry.tar.gz)

**Comment by onpon4** [comment]
I've added this in and will be looking at the others. For future reference, it's much easier to merge a pull request or pull from a Git repo somewhere (where exactly doesn't matter, but if it's in a Git repo I can just do `git remote add <name> <url> && git pull <name> main`).

🕵️
