### ISSUE TITLE
"make install" fails to install "locale/en" folder.

### ISSUE THREAD

**Issue by keikebreau** [pr-starfighter/starfighter#2]
The installation phase fails when installing the "locale/en" folder as part of the "install-nobase_dist_pkgdataDATA" target. When "locale/en" is a file instead of a folder, the installation proceeds as intended. Interestingly, even using "autoreconf -vif" before configuring and building doesn't fix this.

I get the following error during installation on Guix System Distribution...:
> /gnu/store/5s2nib1lrd2101bbrivcl17kjx1mspw6-coreutils-8.30/bin/mkdir -p '/gnu/store/yps0q5cv8zdr9zkxnm7cwk4m3l2r9sl2-starfighter-2.0.0.2/share/starfighter/locale'
 /gnu/store/5s2nib1lrd2101bbrivcl17kjx1mspw6-coreutils-8.30/bin/install -c -m 644  locale/build.py ./locale/en locale/en.po locale/genpot.sh locale/pr-starfighter.pot '/gnu/store/yps0q5cv8zdr9zkxnm7cwk4m3l2r9sl2-starfighter-2.0.0.2/share/starfighter/locale'
/gnu/store/5s2nib1lrd2101bbrivcl17kjx1mspw6-coreutils-8.30/bin/install: omitting directory './locale/en'
make[2]: *** [Makefile:416: install-nobase_dist_pkgdataDATA] Error 1
make[2]: Leaving directory '/tmp/guix-build-starfighter-2.0.0.2.drv-0/starfighter-2.0-src'
make[1]: *** [Makefile:747: install-am] Error 2
make[1]: Leaving directory '/tmp/guix-build-starfighter-2.0.0.2.drv-0/starfighter-2.0-src'
make: *** [Makefile:446: install-recursive] Error 1

...and the same error on Debian Buster:
> /bin/mkdir -p '/home/k/prefix/share/starfighter/music'
 /usr/bin/install -c -m 644  music/death.ogg music/frozen_jam.ogg music/last_cyber_dance.ogg music/orbital_colossus.ogg music/railjet_short.ogg music/RE.ogg music/rise_of_spirit.ogg music/sound_and_silence.ogg music/space_dimensions.ogg music/through_space.ogg music/walking_among_androids.ogg '/home/k/prefix/share/starfighter/music'
 /bin/mkdir -p '/home/k/prefix/share/starfighter/locale'
 /usr/bin/install -c -m 644  locale/build.py ./locale/en locale/en.po locale/genpot.sh locale/pr-starfighter.pot '/home/k/prefix/share/starfighter/locale'
/usr/bin/install: omitting directory './locale/en'
make[2]: *** [Makefile:416: install-nobase_dist_pkgdataDATA] Error 1
make[2]: Leaving directory '/home/k/starfighter-2.0-src'
make[1]: *** [Makefile:747: install-am] Error 2
make[1]: Leaving directory '/home/k/starfighter-2.0-src'
make: *** [Makefile:446: install-recursive] Error 1

To run into this issue, I downloaded the newest [starfighter source tarball](https://github.com/pr-starfighter/starfighter/releases/download/v2.0.0.2/starfighter-2.0-src.tar.gz) and ran the typical "./configure && make && make install" command sequence.

**Comment by onpon4** [comment]
Hm...

Can you try changing this line in Makefile.am:

    nobase_dist_pkgdata_DATA = data/* gfx/* music/* sound/* locale/*

To the following lines?

    nobase_dist_pkgdata_DATA = data/* gfx/* music/* sound/* \
        locale/build.py \
        locale/genpot.sh \
        locale/pr-starfighter.pot \
        locale/en.po \
        locale/en/LC_MESSAGES/pr-starfighter.mo

**Comment by keikebreau** [comment]
Yes. That change fixes the build in both environments.

**Comment by onpon4** [comment]
OK, great! Thank you for the report; I'll integrate this fix later today.

**Comment by timsoftgit** [comment]
great, I was getting the same error with the slackware package script. Will you update the source download package as well?

**Comment by onpon4** [comment]
Yep, I'll be updating both the exported tar/zip files and the auto-generated archives. The only downloads that won't be touched are, once again, the binaries (since they're unaffected by the bug).

**Comment by timsoftgit** [comment]
many thanks, that worked fine. I've updated the starfighter slackbuild to v2.0 so it should be available at slackbuilds.org after the weekend updates go through.

**Comment by onpon4** [comment]
Awesome, thanks!
