### ISSUE TITLE
No sound effects in starfighter 2.3.3: wrong sound files placement at install time

### ISSUE THREAD

**Issue by GvMariani** [pr-starfighter/starfighter#23]
After building and installing starfighter 2.3.3 on my Rosa Fresh 2016.1 (a Mandriva derivative), x86_64,  I found that the game runs well, but without sound effects (music is OK).
Some investigation on the sources showed that at install time the directory "sound" don't get created and all the sound effects files get copied in the "music" directory.

It looks like a couple of typos slipped in commit 8c0df9b3103caa0009b0c5df3aa30ad43df02b84: both sound/Makefile.am and sound/Makefile.in have "sounddir = $(pkgdatadir)/music", while it should be "sounddir = $(pkgdatadir)/sound".

Applying this change and rebuilding configure restores the sound effects.

**Comment by onpon4** [comment]
Wow, that's quite a mistake I made! Thanks for the report. Just pushed a fix. A new release should be coming soon.

🕵️
