### ISSUE TITLE
Words divided into two different lines

### ISSUE THREAD

**Issue by jorgesumle** [pr-starfighter/starfighter#36]
The name is Kris, but the game shows Kri [new line] s

![Captura de pantalla de 2023-05-28 19-06-12](https://github.com/pr-starfighter/starfighter/assets/14212780/0b699cff-cb9c-4abe-b987-e80a972aa43a)

Here it is gvidataj raketoj [new line] ; 

![Captura de pantalla de 2023-05-28 19-07-25](https://github.com/pr-starfighter/starfighter/assets/14212780/3782fd00-b4ec-48b1-aa9e-f340f8dc5724)

... but the semicolon shouldn't be separated.

The strings used in the `.po` file look exactly like the English ones, no newline.

**Comment by onpon4** [comment]
Huh, it looks like there's an error in how it's splitting lines.

I wonder if this might be related to some work we did some time ago to fix Japanese characters getting broken apart at the newline-splitting stage. Perhaps we made a mistake when we fixed that and broke other text, though I don't know why it would affect other Latin script languages but not English. We'll have to look into this.

🦇

**Comment by onpon4** [comment]
I found the problem. Didn't go through all of the game's text to reproduce the exact problem, you mentioned, but I was able to see a related problem where a space got printed at the start of lines after the first one in Esperanto. Both were caused by the same issue: some code was treating a *character* index as if it was a *code point* index when actually performing the line splitting.

**Comment by jorgesumle** [comment]
I've pulled the latest code from this repository and compiled the game again, and I got segmentation fault on a text where the fix is applied. I think this is the message that crashes the game (`src/cutscene.c`, line 113):

`strcpy(messages[2].message, _("What a dilemma! I'm not all that familiar with this ship's controls, but I can't let this patrol reach my rendezvous point..."));`

**Comment by onpon4** [comment]
Damn, guess I'll have to fix that. 😩 Sorry about that, I'll look into it.

**Comment by onpon4** [comment]
I believe I've found the source of a problem. Funny enough, I reproduced it with English more easily. I assume it was
dependent on the exact RAM arrangement. Thanks for telling us about the problem, should be fixed now.

**Comment by jorgesumle** [comment]
Thanks! It doesn't crash now.
