### ISSUE TITLE
gfx/spirit.jpg not found

### ISSUE THREAD

**Issue by metallic77** [pr-starfighter/starfighter#47]
Hi, did a port for armhf 640x480 handheld by 

```
./autogen.sh
./configure --target=arm-linux-gnueabihf --host=arm-linux-gnueabihf SF_RUN_IN_PLACE=1
make
```

When i transfer all to sd card and try to run, it launches and i get an error on screen "gfx/spirit.jpg not found in gfx folder" while it is there, and gfx folder can be accessed by the game because if i remove another file like eg aimFighter1.png, i get error aimFighter1.png not found.
Any clue? 

Cross compiling on a Xenial Docker image
pastebin ./configure output
https://pastebin.com/3T617p34

**Comment by onpon4** [comment]
I assume you're talking about the error displayed on the graphics output that should be worded as I reproduced in this quote block?
> [File name] was not found in the Starfighter data package
> Please try again. If this error persists, contact the authors
> or reinstall the game

That error is primarily meant to be user-facing and not a complete diagnostic, so it'd be good to know what exact output you get in the terminal when you run the game. This particular error only shows up when SDL_image has a problem loading an image from a file, so my first instinct is to suspect there's something wrong with your filesystem or permissions or something (or maybe even that you have one of those fraudulent SD cards which claim to have more capacity than they actually do). But the terminal output should show _exactly_ what error SDL_image encountered, and that should help to make a more accurate and complete diagnosis.

🕷️

**Comment by metallic77** [comment]
System is running on squashfs (internal storage) and there is a folder with extra libs on sd card that contains libSDL2, libSDL2-image etc

When i run ./starfighter executable via puty ssh (no other way to check terminal). 
`Couldn't create or write to "root/.config"`

The error on screen is that message you wrote, stating that gfx/spirit.jpg not found in data package

**Comment by onpon4** [comment]
Well that sounds like a permission error for what it's worth, are permissions restricted on that path? It's attempting to write there for configuration (game settings). It does that for run-in-place builds and expects to have full write access in whatever directory it's in. (Or to be more precise, the current working directory when you run the starfighter binary.) It doesn't have anything to do with the issue loading graphics, thô.

🕷️

**Comment by metallic77** [comment]
Yeah and i created an .sh to launch the game with 
`XDG_CONFIG_HOME="/mnt/SDCARD/Roms/PORTS/starfighter/.config" `

But that didn't help. On /root it can't write, it's a squashfs

**Comment by onpon4** [comment]
You're trying to do a run-in-place build, so that won't affect anything. In run-in-place mode, it always uses whatever the current working directory is; there, it expects to find all the different data folders, and it expects to write to that directory and will put a file called ".config". If you're not in the directory where all the data files are found, you need to switch to that working directory with e.g. the `cd` command. If you *are* in that directory, you need to make sure Starfighter has full write access within that directory. Hope that makes sense?

(EDIT: At least I *think* that's the case. It's been a few years since I touched this code. I could be mistaken.)

🕷️

**Comment by onpon4** [comment]
Scratch that, run-in-place only affects data. I misremembered. I'm not entirely sure what's going on there. In any case, it's unrelated to the graphics loading issue, I think, unless you have some sort of hardware problem. It would help if you could find a way to get the terminal output when it attempts to load the graphics; there should be terminal output lines starting with "Couldn't load" and listing an SDL-generated error.

🕷️

**Comment by metallic77** [comment]
I used another SDL_image and it loads properly now! Sorry for your trouble and thanks for making this great game!
Thanks for the clue with SDL_Image

Any chance you update code with linear filtering? Text looks a bit messy when resizing to 640x480

**Comment by onpon4** [comment]
To be clear, I didn't make it, I just maintain it. 🙂 The original developer is Stephen Sweeney of Parallel Realities. In any case, I'm glad you figured it out!

I'm not familiar with linear filtering, but I certainly wouldn't be against it.

🦇
