### ISSUE TITLE
Add support SDL_GameController

### ISSUE THREAD

**Issue by BeWorld2018** [pr-starfighter/starfighter#7]
Hello,
Very good game, thanks ! i like it :-)

- It's possible to add SDL_GameController support ?
- And maybe add Rumble support for better experience with gamepad/joystick with SDL_GameControllerRumble or SDL_JoystickRumble

Thanks you

**Comment by onpon4** [comment]
It should be possible, yes. What would be the benefits of doing so? It seems to be a more complicated API than the standard joystick API. (But I assume if you're asking for it there must be some gamepads that Starfighter's usage of the standard Joystick API doesn't work well with?)

🕵️

**Comment by BeWorld2018** [comment]
In state with Joystick API, we can't use defined (mapping) button, with it, we can control all... BACK MENU with game pad etc....
Example = A / B X Y of GamePad Xbox360 or PS4 doesnt working....
But Joystick API need to be here for real joystick.

I try to implemented quicly it : 
 
engine.h : (line 110)
```
SDL_GameController *_controller;
SDL_Joystick *_joystick;

```

engine.c (SDL_Init) (add)
`
SDL_INIT_GAMECONTROLLER
`

Replace SDL_JoystickEventState()/SDL_JoystickOpen(0) : 

```
_controller = 0;
_joystick = 0;
if (SDL_NumJoysticks() > 0) {
	if (SDL_IsGameController(0)) {
			SDL_GameControllerEventState(SDL_ENABLE);
			_controller = SDL_GameControllerOpen(0);
				printf("Open GameController : %s\n",SDL_GameControllerName(_controller));
			
			
         }else{
			SDL_JoystickEventState(SDL_ENABLE);
			_joystick = SDL_JoystickOpen(0);
				printf("Open Joystick : %s\n",SDL_JoystickName(_joystick));
	}
		
}
```

Add close Joystick/Gamecontroller when closing game, i put it before SDL_Quit()

```
if (_joystick) {
	SDL_JoystickClose(0);

	_joystick = 0;
}
if (_controller) {
	SDL_GameControllerClose(0);
	_controller = 0;
}

```

Now we have _joystick and _controller available on other class :
Here my code is very light, not finish... but working : 
in player.c - line 311 (after SDL_JOYBUTTONUP:)

```

case SDL_CONTROLLERBUTTONDOWN:
			case SDL_CONTROLLERBUTTONUP:
				switch (engine.event.cbutton.button)
				{
					case SDL_CONTROLLER_BUTTON_A:
					case SDL_CONTROLLER_BUTTON_LEFTSHOULDER:
						engine.keyState[KEY_ALTFIRE] = engine.event.cbutton.state;
						break;
					case SDL_CONTROLLER_BUTTON_B:
					case SDL_CONTROLLER_BUTTON_RIGHTSHOULDER:
						engine.keyState[KEY_FIRE] = engine.event.cbutton.state;
						break;
					case SDL_CONTROLLER_BUTTON_BACK:
					//case 6:
						engine.keyState[KEY_ESCAPE] = engine.event.cbutton.state;
						break;
					case SDL_CONTROLLER_BUTTON_X:
					case SDL_CONTROLLER_BUTTON_Y:
					//case 8:
						engine.keyState[KEY_SWITCH] = engine.event.cbutton.state;
						break;
					case SDL_CONTROLLER_BUTTON_START:
						if (engine.event.cbutton.state)
							engine.keyState[KEY_PAUSE] = 1;
						break;
					/*case SDL_CONTROLLER_BUTTON_DPAD_UP:
						engine.keyState[KEY_UP]    = engine.event.jhat.value & SDL_HAT_UP;
						break;
					case SDL_CONTROLLER_BUTTON_DPAD_DOWN:
						engine.keyState[KEY_DOWN]  = engine.event.jhat.value & SDL_HAT_DOWN;
						break;
					case SDL_CONTROLLER_BUTTON_DPAD_LEFT:
						engine.keyState[KEY_LEFT]  = engine.event.jhat.value & SDL_HAT_LEFT;
						break;
					case SDL_CONTROLLER_BUTTON_DPAD_RIGHT:
						engine.keyState[KEY_RIGHT] = engine.event.jhat.value & SDL_HAT_RIGHT;
						break;*/
				}
				break;


```

To use Rumble, i dont find where i can put it.. i dont test again... :-)

**Comment by onpon4** [comment]
Yes, it seems pretty easy. Some of that code you posted, is that a way to use the game controller API while being able to fall back to the classic joystick API? If so that should be good! Let me know, the API is new to us. 😅

As for rumble I suppose that could be nice for, like, when the player gets hit or something (though I wouldn't consider it essential). We'll look into that. 🙂

Oh! By the way, if you want to contribute code then feel free to make a pull request! 🙂 (If not we'll figure it out, we definitely want to make sure as many game controllers work as possible with this game.)

🕷️

**Comment by BeWorld2018** [comment]
Cool thanks you, no problem, take a time to test :-)

Yes rumble is good little option :-)

i find another little thing, JOYAXISMOTION not working on start menu.

i test and i put this : 

```
case SDL_JOYAXISMOTION:
				val = MIN(1, (double)(abs(engine.event.jaxis.value)) / JS_MAX);
				if (val < JS_DEADZONE)
					val = 0;

				if (engine.event.jaxis.axis == 0) {
					engine.keyState[KEY_LEFT]  =0;
					engine.keyState[KEY_RIGHT] = 0; 		
					engine.xaxis = copysign(val, engine.event.jaxis.value);
					if (engine.xaxis == -1) engine.keyState[KEY_LEFT]=1;
					if (engine.xaxis == 1) engine.keyState[KEY_RIGHT]=1;
				}
				else if (engine.event.jaxis.axis == 1) {
					engine.keyState[KEY_UP]  =0;
					engine.keyState[KEY_DOWN] = 0; 						
					engine.yaxis = copysign(val, engine.event.jaxis.value);
					if (engine.yaxis == -1) engine.keyState[KEY_UP]=1;
					if (engine.yaxis == 1) engine.keyState[KEY_DOWN]=1;
				}

				break;
```

**Comment by onpon4** [comment]
I've fixed the menu issue by simply restoring the old behavior of analog in put for the main menu.

Now to see about the GameController API...

**Comment by onpon4** [comment]
There we go! Implemented. 🙂 It now defaults to the GameController API, unless one of your connected controllers isn't supported, in which case it falls back to the joystick API. (This change also causes all gamepads to be usable.)

🕵️
